---


- name: filter test
  hosts: localhost
  vars:
        names: [ {
        "first": "Paul",
        "last": "Thompson",
        "mobile": "+1-234-31245543",
        "ctc": "100000",
        "address": {
          "city": "LasVegas",
          "country": "USA"
        }
      },
      {
        "first": "Rod",
        "last": "Johnson",
        "mobile": "+1-584-31551209",
        "ctc": "300000",
        "address": {
          "city": "Boston",
          "country": "USA"
        }
      },
      {
        "first": "Sarav",
        "last": "AK",
        "mobile": "+919876543210",
        "ctc": "200000",
        "address": {
          "city": "Chennai",
          "country": "India"
        }
      }]

  tasks:
    - name: Select and Extract only cities
      debug:
        msg: "{{ names | map(attribute='address') | map(attribute='city') }}"

    - name: mobile numbers
      debug:
        msg: "{{ names | map(attribute='mobile') }}"

    - debug: msg={{ names | map(attribute='first') | join(',') }}

    - debug: msg={{ names | map(attribute='last') | map('upper') }}

    - debug: msg={{ names | map(attribute='ctc') | map('float')}}

    - debug: msg={{ names | map(attribute='ctc') | product(['USD']) | map('join', ' ') }}
