---

- name: Patch the server and reboot
  hosts: all
  tasks:
    - name: Patch the server
      become: true
      become_user: root
      tags: patch
      shell: "apt update -y"
      register: patchresult

    - name: Reboot server
      tags: reboot
      become: true
      become_user: root
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0

    - name: Wait for the reboot and connect
      wait_for:
        port: 22
        host: "{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}"
        search_regex: OpenSSH
        delay: 10
        timeout: 60
      connection: local

    - name: Check the uptime of server
      shell: "uptime"
      register: Uptime

    - debug: var=Uptime
